spring.application.name=TodoList
spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
# L?nh b?t bu?c ?? data.sql ch?y sau khi t?o b?ng
spring.jpa.defer-datasource-initialization=true