spring.application.name=TodoList

# C?u hình PostgreSQL (S? d?ng bi?n môi tr??ng do Render cung c?p)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate t? ??ng t?o b?ng
spring.jpa.hibernate.ddl-auto=update